version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs: 
  build:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - run:
          name: Authenticate with GCP
          command: |
            echo $GCLOUD_SERVICE_KEY > file.json
      - run:
          name: Run tests
          command: |
            pip install -r requirements.txt
            python -m unittest discover -s tests -p 'test_*.py'
