version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs: 
  build:
    docker:
      - image: circleci/python:3.11.5
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            pip install -r requirements.txt
            python -m unittest discover -s tests -p 'test_*.py'